language: node_js
node_js:
- '8'
before_install:
 - npm i npm-cli-login -g
 - npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
 - npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "oWkYyEsT6cbI9A/6aW6WHQy5OUolZKX17OVri3fAmX+lJDyKy2DxEA65Z0ZFbx71SFcg+GeJvmX0T/c/lhYSnlH4hMxybktp3pfg+GhN1pHb+NWuC2BciUwZ+fbsRGsIOBVS9cgE5XMDQg08xwnjh+HxJ2I2SWLA87KGR5AJZz/QdJis4/lNBJw7eqW0Wj5sKFmT4hIZbkcqnru+AWyhcjSg7amx5BKcuUmnGBf/Yq5nHyILYsfC5DpdobJeIZo+4GGRi5bdIa3PQpqWsG7+YcGeXvnWAEg7F71KRYZzAJiS3BX/cd/Lk5BWZgO67YH70GPR7Lb2S54vXr/7yyBuwq7y98BVsdJa/bCDF5O0/uJTHRjLjVRj7g5RTIBR6YgzmI6c7TmhOAPMKmT9MRpMFFVrR7rBdBcUHNP7IR/6P6bH1w+uR081h3AoPOB+5lfF2WaWUqOuwS0cWeVTZyRPqiJ9uZbljh1ES4mhu8I8Pd8ifZpue6V4outSQ6eVbNr7O0P3Rrl91iNJta2Kyu0SC6Kykrb1g/0lmvYA6xLZ0C8+xqNmhP1Dg+DkjTSiY342KR4qJoSKtrU4piV1CmI/FvJKoIjUUv4RVLoHJnx4tRPPQYGsTr4BiDM+lqDcILdUDep0umEIC1uThX6qNPwxAVlmTKf7aiFgPZU+xdJNFHE="
